octgnFX/Octgn/Scripting/Versions/3.1.0.0.py
octgnFX/Octgn/Scripting/Versions/3.1.0.1.py
octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_0.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_1.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs

dont hate me too much for changing this :)
using card.anchor will return a True/False
while card.anchor = True/False will set the anchor status
so basically the two anchor functions are merged together.  We should probably do this with a bunch of other API calls at some point.

card.anchor is now a property and a setter

---

octgnFX/Octgn.Library/Schemas/CardGenerator.cs
octgnFX/Octgn.Library/Schemas/CardGenerator.xsd
octgnFX/Octgn.ProxyGenerator/Definitions/SpecialBlockDefinition.cs
octgnFX/Octgn.ProxyGenerator/ProxyGenerator.cs
octgnFX/Octgn.ProxyGenerator/Util/GraphicUtils.cs

added mandatory size element to artoverlay

brines changes and mine.

---

octgnFX/Octgn.Core/DataExtensionMethods/CardExtensionMethods.cs

card alternates work with proxy art crops

---

octgnFX/Octgn/Play/Dialogs/PickCardsDialog.xaml

As asked I'm opening this pull request on the test branch
At least I hope I'm , I usually work with SVN , GIT is still a bit strange to me

Readability for the amount of cards left in a filter for the PickCardsDialog

---

octgnFX/Octgn/Play/Actions/Move.cs
octgnFX/Octgn/Scripting/GameEvents.cs

- replaces redundant onScriptMove parameter in 3.1.0.1 API version

#1374 onMoveCard events pass onFaceUp card status

---

octgnFX/Octgn.Library/Schemas/GameEvents.xsd
octgnFX/Octgn.Library/Scripting/GameEvents.xml
octgnFX/Octgn/Scripting/GameEvents.cs

fixes #1374 onMoveCard events pass onFaceUp card status

update to #1403 pull request

---

octgnFX/Octgn/Play/PlayWindow.xaml

I threw it together to test what I wanted it to look like, so it's a
silly way to do it, but I like how it turned out, so I don't really care
to change it. anybody who cares is welcome to though.

visual update for resizing player area

---

octgnFX/Octgn/Utils/UiWatcher.cs
recentchanges.txt

Made lag window wait 1 second to display

Fixed lag window to not display after window is shut

---

octgnFX/Octgn/Scripting/Controls/SelectCardsDlg.xaml.cs
octgnFX/Octgn/Scripting/Controls/SelectMultiCardsDlg.xaml.cs
octgnFX/Octgn/Scripting/Versions/3.1.0.0.py
octgnFX/Octgn/Scripting/Versions/3.1.0.1.py
octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_0.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_1.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

using selectCard with max=1 and min=1 will use the old single-select dialog; filter box works now

some ugprades to the selectCard API

---

octgnFX/Octgn/Networking/ClientHandler.cs
octgnFX/Octgn/Play/Actions/Target.cs
octgnFX/Octgn/Play/Card.cs
octgnFX/Octgn/Play/Counter.cs
octgnFX/Octgn/Play/Gui/ChatControl.xaml
octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs
recentchanges.txt

some issues with card anchoring and game event notifications

---

octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs
recentchanges.txt

hide error/debug checkboxes will now hide/show the entire chat log

---

octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml
octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs
octgnFX/Octgn/DeckBuilder/SearchControl.xaml
recentchanges.txt

add ability to sort deck sections fix #654

---

octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
recentchanges.txt

make sure to enable 3.1.0.2 to Live before pulling this PR.

last chance python API updates

---

octgnFX/Octgn/Play/Gui/TableControl.xaml
octgnFX/Octgn/Play/Gui/TableControl.xaml.cs
recentchanges.txt

todo: add click-drag and right-click support for cards on the table (currently it doesn't detect any cards and will move/zoom the table)

multi-touch support for table

---

octgnFX/Octgn/Scripting/Controls/SelectMultiCardsDlg.xaml
octgnFX/Octgn/Scripting/Controls/SelectMultiCardsDlg.xaml.cs
octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

Should be proof-read and bug-tested with another set of eyes, as I'm sure there's more professional-looking ways to handle what I've done.
addresses issue #377

added drag/drop to python cardDlg API

---

octgnFX/Octgn.Server/BinaryParser.cs
octgnFX/Octgn.Server/BinaryStubs.cs
octgnFX/Octgn.Server/Broadcaster.cs
octgnFX/Octgn.Server/Handler.cs
octgnFX/Octgn.Server/IClientCalls.cs
octgnFX/Octgn.Server/Protocol.xml
octgnFX/Octgn/Controls/PreGameLobby.xaml.cs
octgnFX/Octgn/Networking/BinaryParser.cs
octgnFX/Octgn/Networking/BinaryStubs.cs
octgnFX/Octgn/Networking/ClientHandler.cs
octgnFX/Octgn/Networking/IServerCalls.cs
octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs
octgnFX/Octgn/Play/Player.cs
octgnFX/Octgn/Play/State/GameSaveState.cs
octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

Allow player color to be set through Python

---

octgnFX/Octide/ViewModel/TableTabViewModel.cs
recentchanges.txt

no guarantees it functionally works, but at least it wont error out anymore

octide wont error out anymore -- still garbo tho

---

octgnFX/Octgn.Library/FeedProvider.cs
recentchanges.txt

This reverts commit 90a4a15a29062429e9898df1c1e2ad9effa71c0c.

Revert "Disable online feeds for now."

---

octgnFX/Octgn/Controls/DecorableWindow.cs
recentchanges.txt

Fixed issue with DecorableWindow not handling multiple screens correctly when moving the window

Multiple screens issue with window decorators

---

octgnFX/Octgn.Core/DataExtensionMethods/PackExtensionMethods.cs
octgnFX/Octgn.DataNew/Entities/Include.cs
octgnFX/Octgn.DataNew/Entities/Pack.cs
octgnFX/Octgn.DataNew/Entities/Pick.cs
octgnFX/Octgn.DataNew/GameSerializer.cs
octgnFX/Octgn.DataNew/Octgn.DataNew.csproj
octgnFX/Octgn.Library/Schemas/CardSet.cs
octgnFX/Octgn.Library/Schemas/CardSet.xsd
recentchanges.txt

+- Can define additional properties to match with for card pack generator
+- Can include cards from other set defs within specific card packs
+- Can define alternative property values to cards included from other sets

multi-property matching and including cards from other sets in booster gen

---

octgnFX/Octgn.Library/Scripting/GameEvents.xml
octgnFX/Octgn/Networking/ClientHandler.cs
octgnFX/Octgn/Scripting/GameEvents.cs
recentchanges.txt

added OnCardControllerChanged event to 3.1.0.2 API

---

octgnFX/Octgn.DataNew/Entities/Group.cs
octgnFX/Octgn.DataNew/GameSerializer.cs
octgnFX/Octgn.Library/Schemas/Game.cs
octgnFX/Octgn.Library/Schemas/Game.xsd
octgnFX/Octgn/Play/Gui/GroupControl.cs
recentchanges.txt

plz review and get tested before merge

showName tag added to group/card actions, showIf can be used for groupaction

---

octgnFX/Octgn/Octgn.csproj
octgnFX/Octgn/Scripting/Controls/PackDlg.xaml
octgnFX/Octgn/Scripting/Controls/PackDlg.xaml.cs
octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

choosePack() opens a dialog to choose a card pack, returns its GUID
generatePack(packId) API returns list of card GUIDs from OCTGN's pack generator.

choosePack() and generatePack() API for interacting with card packs

---

octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

squeeze this in before people start using this function, as it changes the return data (for the better tho).

choosePack() returns tuple (setName, packName, packID), more useful

---

octgnFX/Octgn/Play/Gui/GroupControl.cs
octgnFX/Octgn/Play/Gui/TableControl.xaml.cs
octgnFX/Octgn/Scripting/Engine.cs
recentchanges.txt

showIf and getName action tags now pass group and table coordinates

---

octgnFX/Octgn.Library/Scripting/GameEvents.xml
octgnFX/Octgn/Play/Actions/Move.cs
octgnFX/Octgn/Scripting/GameEvents.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

added 'alternates' and 'filters' arguments to 3.1.0.2 CardsMoved events

cleaned up move.cs and fixed some issues with queryCard API

---

octgnFX/Octgn/Play/Dialogs/PickCardsDialog.xaml.cs
recentchanges.txt

Fix scroll positon in Limited Deck Builder

---

octgnFX/Octgn.Library/Octgn.Library.csproj
octgnFX/Octgn.Library/packages.config
octgnFX/Octgn.Online.CommunicationService/Octgn.Online.CommunicationService.csproj
octgnFX/Octgn.Online.CommunicationService/packages.config
octgnFX/Octgn.Online.GameService/Octgn.Online.GameService.csproj
octgnFX/Octgn.Online.GameService/packages.config
octgnFX/Octgn.Online.StandAloneServer/Octgn.Online.StandAloneServer.csproj
octgnFX/Octgn.Online.StandAloneServer/packages.config
octgnFX/Octgn.Online/Hosting/HostedGame.cs
octgnFX/Octgn.Online/Octgn.Online.csproj
octgnFX/Octgn.Server/Octgn.Server.csproj
octgnFX/Octgn.Server/packages.config
octgnFX/Octgn.Test/Octgn.Test.csproj
octgnFX/Octgn.Test/packages.config
octgnFX/Octgn.WindowsDesktopUtilities/Octgn.WindowsDesktopUtilities.csproj
octgnFX/Octgn.WindowsDesktopUtilities/packages.config
octgnFX/Octgn/Octgn.csproj
octgnFX/Octgn/packages.config

More com updates

---

octgnFX/Octgn.Server/Handler.cs
octgnFX/Octgn/Controls/HostGameSettings.xaml
octgnFX/Octgn/Controls/HostGameSettings.xaml.cs
octgnFX/Octgn/Tabs/Play/PlayTab.xaml

Fixed username not showing up in game list

Fixed a few bugs

---

octgnFX/Octgn/Play/Player.cs

If no UserId specified(because it's a local game), then create one.

Fixes offline games

---

octgnFX/Octgn.Library/Networking/GameBroadcastListener.cs
octgnFX/Octgn.Library/Networking/GameBroadcaster.cs
octgnFX/Octgn/Tabs/Play/PlayTab.xaml.cs

If no UserId specified(because it's a local game), then create one.

Fixes multiple instances of OCTGN running at once

---

octgnFX/Octgn.Core/Util/TextUploader.cs
recentchanges.txt

Fixed log sharing.

---

octgnFX/Octgn/Controls/HostGameSettings.xaml.cs

If ApiUser is null, return null IconUrl

Fix hosting lan when online

---

octgnFX/Octgn.Server/BinaryParser.cs
octgnFX/Octgn.Server/BinaryParser.tt
octgnFX/Octgn.Server/BinaryStubs.cs
octgnFX/Octgn.Server/BinaryStubs.tt
octgnFX/Octgn.Server/GameContext.cs
octgnFX/Octgn.Server/ServerSocket.cs
octgnFX/Octgn/Networking/BinaryParser.cs
octgnFX/Octgn/Networking/BinaryParser.tt
octgnFX/Octgn/Networking/BinaryStubs.cs
octgnFX/Octgn/Networking/BinaryStubs.tt

Convert some of the muted stuff back to int
Moved IsMuted on the server to from ServerSocket to GameContext to put it into the context of all the players, instead of each user haveing their own muted.

Fixed muted

---

.gitmodules
OCTGN.sln
octgnFX/Octgn.Library/Octgn.Library.csproj
octgnFX/Octgn.Library/packages.config
octgnFX/Octgn.Online.CommunicationService.InstallerLib/HeatGeneratedFileList.wxs
octgnFX/Octgn.Online.CommunicationService/Octgn.Online.CommunicationService.csproj
octgnFX/Octgn.Online.CommunicationService/packages.config
octgnFX/Octgn.Online.GameService.InstallerLib/HeatGeneratedFileList.wxs
octgnFX/Octgn.Online.GameService/App.config
octgnFX/Octgn.Online.GameService/Octgn.Online.GameService.csproj
octgnFX/Octgn.Online.GameService/packages.config
octgnFX/Octgn.Online.StandAloneServer/Octgn.Online.StandAloneServer.csproj
octgnFX/Octgn.Online.StandAloneServer/packages.config
octgnFX/Octgn.Online/Octgn.Online.csproj
octgnFX/Octgn.Server/Octgn.Server.csproj
octgnFX/Octgn.Server/packages.config
octgnFX/Octgn.Test/Octgn.Test.csproj
octgnFX/Octgn.Test/packages.config
octgnFX/Octgn.WindowsDesktopUtilities/Octgn.WindowsDesktopUtilities.csproj
octgnFX/Octgn.WindowsDesktopUtilities/packages.config
octgnFX/Octgn/Octgn.csproj
octgnFX/Octgn/packages.config

Also dealt with some noisy logs

Added Octgn.Communication as submodule

---

octgnFX/Octgn.Server/Handler.cs
octgnFX/Octgn.Server/Player.cs
recentchanges.txt

fixed player side bug (inverted table)

---

CHANGELOG.md
Version.cs
octgnFX/Octgn.Online/Octgn.Online.csproj
octgnFX/Octgn/Play/Player.cs

Fixed player color assignment crashing with large player IDs

---

octgnFX/Octgn.Core/GameSettings.cs
octgnFX/Octgn.DataNew/DbContext.cs
octgnFX/Octgn.DataNew/Entities/Game.cs
octgnFX/Octgn.DataNew/Entities/Pick.cs
octgnFX/Octgn.DataNew/Entities/PickProperty.cs
octgnFX/Octgn.DataNew/ExtensionMethods.cs
octgnFX/Octgn.DataNew/FileDB/FileDbConfiguration.cs
octgnFX/Octgn.DataNew/GameSerializer.cs
octgnFX/Octgn.DataNew/Octgn.DataNew.csproj
octgnFX/Octgn.Library/Schemas/CardSet.cs
octgnFX/Octgn.Library/Schemas/CardSet.xsd
octgnFX/Octgn.Library/Schemas/Game.cs
octgnFX/Octgn.Library/Schemas/Game.xsd
octgnFX/Octgn.ProxyGenerator/BlockManager.cs
octgnFX/Octgn.ProxyGenerator/TemplateManager.cs
octgnFX/Octgn/Controls/PreGameLobby.xaml
octgnFX/Octgn/Controls/PreGameLobby.xaml.cs
octgnFX/Octgn/Play/PlayWindow.xaml
octgnFX/Octgn/Play/PlayWindow.xaml.cs
octgnFX/o8build/GameValidator.cs
recentchanges.txt

my local octide branch had a bunch of updates to the game serializer, which I separated out and opened as this pull request.  A lot of it is XML serializer code which the IDE needed to create the xml files, but there's some optimizations and validation requirements that were tweaked over time in here too.  I also included the code that allows a custom game database location, I feel like it can be useful outside of the IDE as well.

some gameserializer related work

---

octgnFX/Octgn/DeckBuilder/FilterControl.xaml.cs
recentchanges.txt

turns out that was pretty easy once I can finally build

removed rogue comma, fixes #1695

---

octgnFX/Octgn.Core/Play/GameMessageDispatcher.cs
octgnFX/Octgn.Core/Prefs.cs
octgnFX/Octgn.DataNew/Entities/Font.cs
octgnFX/Octgn.DataNew/GameSerializer.cs
octgnFX/Octgn.Library/Schemas/Game.cs
octgnFX/Octgn.Library/Schemas/Game.xsd
octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs
octgnFX/Octgn/Extentions/ExtensionMethods.cs
octgnFX/Octgn/Networking/ClientHandler.cs
octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs
octgnFX/Octgn/Play/Gui/NoteControl.xaml.cs
octgnFX/Octgn/Play/PlayWindow.xaml
octgnFX/Octgn/Play/PlayWindow.xaml.cs
octgnFX/Octgn/Play/Player.cs
octgnFX/Octgn/Play/State/GameEngine.cs
octgnFX/Octgn/Play/State/GameSaveState.cs
octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_0.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_1.cs
octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
octgnFX/o8build/GameValidator.cs
recentchanges.txt

more fixes

---

octgnFX/Octgn/Controls/PreGameLobby.xaml
octgnFX/Octgn/Play/Player.cs
octgnFX/Octgn/Scripting/Engine.cs
recentchanges.txt

some spectator bugs

---

octgnFX/Octgn/Play/Gui/TableControl.xaml
octgnFX/Octgn/Play/Gui/TableControl.xaml.cs
recentchanges.txt

Fix selection dialog being stuck on game table

---

octgnFX/Octgn/Play/Gui/TableControl.xaml
octgnFX/Octgn/Play/Gui/TableControl.xaml.cs
recentchanges.txt

Fixed zoom bug where zooming out could invert table and cause crash - Kelly
Made mouse wheel zoom and keyboard zoom consistent regardless of zoom level - Kelly

Zoom improvements

---

octgnFX/Octgn/DeckBuilder/FilterControl.xaml.cs
recentchanges.txt

fixed OR searching everything

---

octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs
octgnFX/Octgn/Windows/Main.xaml.cs
recentchanges.txt

Fixes #1798
I broke the original pull request https://github.com/octgn/OCTGN/pull/1830

makes main window close respect deck editor cancel

---

octgnFX/Octgn.Core/DataExtensionMethods/DeckExtensionMethods.cs
octgnFX/Octgn/Controls/HostGameSettings.xaml.cs
octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml
octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs
octgnFX/Octgn/DeckBuilder/SearchControl.xaml.cs
octgnFX/Octgn/Play/PlayWindow.xaml.cs
recentchanges.txt

Did a bunch of stuff to improve the deck editor, mostly hotkey behavior.

Deck editor

---

octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs
octgnFX/Octgn/DeckBuilder/FilterControl.xaml.cs
octgnFX/Octgn/DeckBuilder/SearchControl.xaml.cs
recentchanges.txt

And fix closing editor if main window closed while editor is safe to close (not unsaved)
oh, and more restrictions on instant searching to hopefully improve performance

More deck editor hotkey improvements

---

octgnFX/Octgn/DeckBuilder/FilterControl.xaml.cs
octgnFX/Octgn/DeckBuilder/SearchControl.xaml.cs

removed looping behavior at bottom and bouncing off of top?
added home and end behavior

fixed navigating off end of search grid

---

octgnFX/Octgn/Play/State/GameEngine.cs

Fixes replay saving with invalid characters in game names.

Fix OCTGN crashing while attempting to save a replay

---

octgnFX/Octgn/CommandLineHandler.cs
octgnFX/Octgn/Launchers/DeckEditorLauncher.cs
recentchanges.txt

without specifying a deck
uses -e | -editor

allow launching deck editor directly

---

octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml
octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs
recentchanges.txt

I'm not even sure how or why, but this works better.
fixes #1841
(hopefully?)
adds #1885

deck editor improvements

---

octgnFX/Octgn/Tabs/GameHistory/GameHistoryTab.xaml.cs

fixes for lots of users crashing

Fix com server breaking games

---

octgnFX/Octgn.Core/Prefs.cs
octgnFX/Octgn/Tabs/GameHistory/GameHistoryTab.xaml
octgnFX/Octgn/Tabs/GameHistory/GameHistoryTab.xaml.cs
recentchanges.txt

Paginate History Tab

---

octgnFX/Octgn.Online/Hosting/HostedGameProcess.cs
octgnFX/Octgn.Server/GameContext.cs
octgnFX/Octgn.Server/GameState.cs
octgnFX/Octgn.Server/PlayerCollection.cs

also removed unnecessary erroring out when starting local server
I'm guessing you had some goal in mind for the changes you were making that this doesn't meet, but I figure I'll put it up since I have it.

resolve server crash on start

---

octgnFX/Octgn/Play/Player.cs

put global player back in front

---

octgnFX/o8build/GameValidator.cs
octgnFX/o8build/Program.cs

o8build fixes

---

octgnFX/Octgn/Controls/NumericUpDown.cs
octgnFX/Octgn/Controls/WindowDecorators/OctgnDecorator.cs
octgnFX/Octgn/Play/Card.cs
octgnFX/Octgn/Play/Gui/CardControl.xaml
octgnFX/Octgn/Play/Gui/CardControl.xaml.cs
octgnFX/Octgn/Play/Gui/MarkerControl.xaml
octgnFX/Octgn/Play/Gui/PlayerControl.xaml
octgnFX/Octgn/Play/Gui/TableControl.xaml
recentchanges.txt

hopefully this will allow some screen readers to get card names and text.
adds card text tooltip to cards when ctrl is held.
also add tooltip/name to octgn window decoration min/max/close buttons.

Add some accessibility behaviors

---

octgnFX/Octgn/Play/Gui/CardControl.xaml.cs
recentchanges.txt

Fix a tooltip crash

---

HACK.md

Tips to get development started

Dev Setup Instructions

---

octgnFX/Octgn/Controls/RichTextBlock.cs
octgnFX/Octgn/DeckBuilder/SearchControl.xaml.cs
octgnFX/Octgn/Octgn.csproj
octgnFX/Octgn/Play/Card.cs
octgnFX/Octgn/Play/Gui/CardControl.xaml.cs
octgnFX/Octgn/Utils/Converters/RichTextConverter.cs

rich text tooltips!

---

octgnFX/Octgn.JodsEngine/DeckBuilder/DeckBuilderWindow.xaml.cs
octgnFX/Octgn.JodsEngine/DeckBuilder/SearchSave.cs
recentchanges.txt

also more detailed error logs if the search save doesn't load
closes #2051

loading multiple search saves at once in the deck editor

---

octgnFX/Octgn.DataNew/GameSerializer.cs
octgnFX/Octgn.Library/Schemas/Game.cs
octgnFX/Octgn.Library/Schemas/Game.xsd
octgnFX/o8build/GameValidator.cs

o8build validator won't be as annoying when unused attributes show up in group or table elements

streamlined the table/pile derived group schemas

---

octgnFX/Octgn.JodsEngine/Play/Gui/ChatControl.xaml
octgnFX/Octgn.JodsEngine/Play/Gui/FanPanel.cs
octgnFX/Octgn.JodsEngine/Play/Gui/PileControl.xaml
octgnFX/Octgn.JodsEngine/Play/Gui/PileControl.xaml.cs
octgnFX/Octgn.JodsEngine/Play/PlayWindow.xaml
recentchanges.txt

Minor accessibility updates
Improve card fan performance

Couple small things

---

octgnFX/Octgn.DataNew/Entities/Card.cs

fixed a bug in the deprecated Card.Properties dictionary

---

octgnFX/Octgn.JodsEngine/Networking/BinaryParser.cs
octgnFX/Octgn.JodsEngine/Networking/IServerCalls.cs
octgnFX/Octgn.JodsEngine/Play/Gui/GroupControl.cs
octgnFX/Octgn.JodsEngine/Play/State/GroupSaveState.cs
octgnFX/Octgn.Server/Protocol.xml

Adds a spectators submenu within group visibility so players can toggle visibility of groups to spectators

players can add spectators to their group visibility

---

octgnFX/Octgn.JodsEngine/Networking/BinaryParser.cs
octgnFX/Octgn.JodsEngine/Networking/BinaryStubs.cs
octgnFX/Octgn.JodsEngine/Networking/ClientHandler.cs
octgnFX/Octgn.JodsEngine/Networking/IServerCalls.cs
octgnFX/Octgn.JodsEngine/Play/Dialogs/LimitedDialog.xaml.cs
octgnFX/Octgn.JodsEngine/Play/Gui/Commands.cs
octgnFX/Octgn.JodsEngine/Play/PlayWindow.xaml
octgnFX/Octgn.JodsEngine/Play/PlayWindow.xaml.cs
octgnFX/Octgn.JodsEngine/Play/Save/ReplayEngine.cs
octgnFX/Octgn.JodsEngine/Play/State/GameEngine.cs
octgnFX/Octgn.JodsEngine/Scripting/GameEvents.cs
octgnFX/Octgn.JodsEngine/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_0.cs
octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_1.cs
octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_2.cs
octgnFX/Octgn.Library/Scripting/GameEvents.xml
octgnFX/Octgn.Server/BinaryParser.cs
octgnFX/Octgn.Server/BinaryStubs.cs
octgnFX/Octgn.Server/Broadcaster.cs
octgnFX/Octgn.Server/GameContext.cs
octgnFX/Octgn.Server/Handler.cs
octgnFX/Octgn.Server/IClientCalls.cs
octgnFX/Octgn.Server/Protocol.xml
octgnFX/Octgn/JodsEngineIntegration.cs
recentchanges.txt

a bunch of random bug fixes and a few minor features/addons

bunch of fixes incoming

---

octgnFX/Octgn/Controls/HostGameSettings.xaml.cs
octgnFX/Octgn/JodsEngineIntegration.cs

Fix hosting online game launches stand alone server

---

octgnFX/Octgn.JodsEngine/Play/Gui/TableControl.xaml.cs
octgnFX/Octgn.JodsEngine/Play/State/GameEngine.cs
octgnFX/Octgn.JodsEngine/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_2.cs
recentchanges.txt

Gives python api methods to control the view of the table

Refit and reset table view controls

---

octgnFX/Octgn.JodsEngine/Play/Gui/FanPanel.cs

revert some superfluous changes made in f3e0a20c2 to fix strange zooming behavior when dragging in certain cases

fixed card zoom

---

octgnFX/Octgn.DataNew/GameSerializer.cs
octgnFX/Octgn.JodsEngine/Play/Dialogs/RulesWindow.xaml.cs
recentchanges.txt

got rid of the try/catch for the deprecated game board code, game document name shows up in the window's title

couple fixes

---

octgnFX/Octgn.Core/DiscordIntegration/DiscordWrapper.cs

re-submitted from a previous closed pull request

Fixes #2120. Don't attempt to dispose a null value in iscord wrapper

---

OCTGN.sln
octgnFX/Octgn.InstallerLib/HeatGeneratedFileList.wxs
octgnFX/Octgn.InstallerLib/Octgn.InstallerLib.wixproj
octgnFX/Octgn.JodsEngine/CommandLineHandler.cs
octgnFX/Octgn.JodsEngine/DesktopIntegration/DesktopDbContext.cs
octgnFX/Octgn.JodsEngine/DesktopIntegration/JodsGameFormat.cs
octgnFX/Octgn.JodsEngine/DesktopIntegration/JodsGameMenu.cs
octgnFX/Octgn.JodsEngine/DesktopIntegration/JodsGamePlugin.cs
octgnFX/Octgn.JodsEngine/DesktopIntegration/SinglePlayerMenuItem.cs
octgnFX/Octgn.JodsEngine/Octgn.JodsEngine.csproj
octgnFX/Octgn.Online.CommunicationService.InstallerLib/HeatGeneratedFileList.wxs
octgnFX/Octgn.Online.CommunicationService.InstallerLib/Octgn.Online.CommunicationService.InstallerLib.wixproj
octgnFX/Octgn.Online.GameService.InstallerLib/HeatGeneratedFileList.wxs
octgnFX/Octgn.Online.GameService.InstallerLib/Octgn.Online.GameService.InstallerLib.wixproj

Updated the communication library submodule
Removed desktop integration from the JodsEngine program
Fix a build issue with wix in visual studio causing it to crash
Updated sln to use vs2022
Updated the installer file lists

Wix updates and fix sum build issues

---

octgnFX/Octgn.JodsEngine/Play/Card.cs
octgnFX/Octgn.JodsEngine/Scripting/Versions/3.1.0.2.py
octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_2.cs
octgnFX/Octgn.Library/SavedPasswordManager.cs
recentchanges.txt

Re-submitted, removing the 4.8 .NET update commit (since we're not doing that)

Itsy bitsy fixes

---

.vscode/settings.json
README.md
octgnFX/Octgn/CommandLineHandler.cs
octgnFX/Octgn/Launchers/UpdatingLauncher.cs
recentchanges.txt

- Added --skip-update/-n flag to bypass automatic update checks on startup
- Added --help/-h flag with comprehensive command line documentation
- Enhanced command line argument descriptions for all existing options
- Updated README.md with complete command line usage documentation
- Added VS Code workspace configuration for better development experience
- Improved error handling and user feedback for command line operations

Add command line improvements with skip updates and help features
