octgn/OCTGN

octgnFX/Octgn/Scripting/PythonAPI.py, octgnFX/Octgn/Scripting/Versions/3.1.0.0.py, octgnFX/Octgn/Scripting/Versions/3.1.0.1.py, octgnFX/Octgn/Scripting/Versions/3.1.0.2.py
To simplify comparison of Card, NamedObject, and Player objects with non-OCTGN (such as "some_variable == some_card"), check that the other object actually has an ._id attribute. Otherwise, an exception is thrown, thus requiring more of verbosity higher up to avoid this.
=> Check for _id attr in __cmp__ methods

octgnFX/Octgn/Controls/CustomGames.xaml, octgnFX/Octgn/Controls/FeatureFundingMessage.xaml, octgnFX/Octgn/Tabs/GameManagement/GameManagement.xaml, octgnFX/Octgn/Tabs/Login/LoginNew.xaml, octgnFX/Octgn/Tabs/Login/LoginNew.xaml.cs, octgnFX/Octgn/Windows/Main.xaml
- fixed buttons and menus that were too small to fit the text (possibly due to my non-standard default Windows font size)
- login tab: fixed username/password heights; fixed width jump when start typing; fixed right align; fixed the visual vertical separator
Screenshots:
- http://i.imgur.com/aFGPvym.png
- http://i.imgur.com/CticLoR.png
- http://i.imgur.com/WWpuRyN.png
=> Visual polish:

octgnFX/Octgn/Play/Actions/Move.cs, octgnFX/Octgn/Play/Card.cs
onMoveCards wasn't being triggered when a card was moved within a group,
since it wasn't checking for changes to just a card's index.
=> fixed onMoveCards w. moving card within a group

octgnFX/Octgn/Scripting/Versions/Script_3_1_0_1.cs
this change was previously done in 3.1.0.0 but someone must have forgotten to copy it in 3.1.0.1
=> fix #1426 card.model not working for face-down cards in 3.1.0.1 API

octgnFX/Octgn/DeckBuilder/DeckEditorPreviewControl.xaml.cs, recentchanges.txt
This was causing images in the deck editor preview not to show if the color profile in the image was corrupted.
=> Ignore color profile so corrupt color profiles don't break image loading

octgnFX/Octgn/Play/Gui/ChatControl.xaml, octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs, octgnFX/Octgn/Play/PlayWindow.xaml.cs, recentchanges.txt
size defined in game fonts no longer serves a purpose, I have no idea if o8build needs to be updated.
=> Make game chat obey user font size setting

octgnFX/Octgn.Core/DataExtensionMethods/GameExtensionMethods.cs, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs, octgnFX/Octgn/DeckBuilder/DeckEditorPreviewControl.xaml.cs, octgnFX/Octgn/DeckBuilder/SearchControl.xaml.cs, recentchanges.txt
This just adds all alternate versions of a card to the deck editor's data grid, allowing them to show up when the user creates filters.  Works with subscriber drag/drop images as well.
no mechanism to hide alternates yet, if someone feels this is important please add it in.
=> all alternates show up in deck editor data grid

octgnFX/Octgn.Core/DataExtensionMethods/CardExtensionMethods.cs, octgnFX/Octgn/DeckBuilder/DeckEditorPreviewControl.xaml.cs, recentchanges.txt
Alternate card images load properly when the base card image is missing
=> fixed #1578 issues with alternate card image fetching

octgnFX/Octgn.Core/Prefs.cs, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs, octgnFX/Octgn/Octgn.csproj, octgnFX/Octgn/Windows/ImportImages.xaml, octgnFX/Octgn/Windows/ImportImages.xaml.cs, recentchanges.txt
sooooo I have  no idea if we actually want to keep this within the program, or pull it out into a deck editor plugin.  It's not very pretty but it works.
I have a basic string sanitizer function that's used to compare the filename to a matched card property, I'm not good with regex or smart matching functions so if anyone has any cool ideas feel free to improve it.
Also, I kept the subscriber lock on it, unsure if we still care about that or not.
=> bulk image importer added to deck editor (sub only)

octgnFX/Octgn.Core/Play/GameMessageDispatcher.cs, octgnFX/Octgn.DataNew/Entities/Game.cs, octgnFX/Octgn.DataNew/Entities/GamePhase.cs, octgnFX/Octgn.DataNew/GameSerializer.cs, octgnFX/Octgn.DataNew/Octgn.DataNew.csproj, octgnFX/Octgn.Library/Schemas/Game.cs, octgnFX/Octgn.Library/Schemas/Game.xsd, octgnFX/Octgn.Library/Scripting/GameEvents.xml, octgnFX/Octgn.Server/BinaryParser.cs, octgnFX/Octgn.Server/BinaryStubs.cs, octgnFX/Octgn.Server/Broadcaster.cs, octgnFX/Octgn.Server/Handler.cs, octgnFX/Octgn.Server/IClientCalls.cs, octgnFX/Octgn.Server/Protocol.xml, octgnFX/Octgn/Networking/BinaryParser.cs, octgnFX/Octgn/Networking/BinaryStubs.cs, octgnFX/Octgn/Networking/ClientHandler.cs, octgnFX/Octgn/Networking/IServerCalls.cs, octgnFX/Octgn/Octgn.csproj, octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs, octgnFX/Octgn/Play/Gui/TableControl.xaml.cs, octgnFX/Octgn/Play/Phase.cs, octgnFX/Octgn/Play/PlayWindow.xaml, octgnFX/Octgn/Play/PlayWindow.xaml.cs, octgnFX/Octgn/Play/State/GameEngine.cs, octgnFX/Octgn/Scripting/GameEvents.cs, octgnFX/Octgn/Scripting/Versions/3.1.0.2.py, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs, recentchanges.txt
Adds a phase toolbar to the top-right corner of the play table, which displays the active player name and the current phase name.  Hovering over the toolbar will animate a list of available clickable phases, active player can request phase changes and nonactive players can pause the phase (similar to the pass turn buttons).  Clicking the toolbar will anchor the phase list, so it doesn't disappear.
XML game definition, goes in between 'proxygen' and 'documents'
```xml
<phases>
<phase name="Main Phase" icon="phases/mainphase.png" />
<phase name="Battle Phase" icon="phases/battlephase.png" />
</phases>
```
Phases are indexed according to their sequential order listed in the XML, starting at 1 (0 is a null default phase)
python controls:
```python
print currentPhase()
>> ("Main Phase", 1) …
```
=> support for Game Phases

octgnFX/Octgn.Library/Scripting/GameEvents.xml, octgnFX/Octgn.Server/BinaryParser.cs, octgnFX/Octgn.Server/BinaryStubs.cs, octgnFX/Octgn.Server/Broadcaster.cs, octgnFX/Octgn.Server/Handler.cs, octgnFX/Octgn.Server/IClientCalls.cs, octgnFX/Octgn.Server/Protocol.xml, octgnFX/Octgn/Networking/BinaryParser.cs, octgnFX/Octgn/Networking/BinaryStubs.cs, octgnFX/Octgn/Networking/ClientHandler.cs, octgnFX/Octgn/Networking/IServerCalls.cs, octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs, octgnFX/Octgn/Play/PlayWindow.xaml, octgnFX/Octgn/Play/PlayWindow.xaml.cs, octgnFX/Octgn/Play/State/GameEngine.cs, octgnFX/Octgn/Resources/Themes/BlueGlass/Button.xaml, octgnFX/Octgn/Scripting/GameEvents.cs, octgnFX/Octgn/Scripting/Versions/3.1.0.0.py, octgnFX/Octgn/Scripting/Versions/3.1.0.1.py, octgnFX/Octgn/Scripting/Versions/3.1.0.2.py, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_0.cs, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_1.cs, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs, recentchanges.txt
- Phases now cycle sequentially, active player will set stops on phases instead of jumping between them
- Phase stops will persist between turns
- Clicking the "Pass turn" green arrow button on the player tab will sequentially scan through phases and pause on the first phase that has a stop set.  If there are no stopped phases, it will pass the turn to the next player (old functionality)
- Added OverridePhaseClicked and OverrideTurnPassed override events to control the functionality of the Pass Turn and phase buttons
- Added several python API calls to provide greater control over changing turns, changing phases, changing active player, toggling stops
- Fixed a visual bug involving the play/pause turn buttons on the player tab
=> Major changes to the Phase system

octgnFX/Octgn/Tabs/Watch/WatchList.xaml.cs
v3 has been deprecated in 2018 and will be removed at the end of 2018
This also fixes the incorrect results (old API returned items matching "octane" when searching for "octgn")
https://dev.twitch.tv/docs/v5
=> Update twitch API to v5

octgnFX/Octgn.Online.StandAloneServer/App.config, octgnFX/Octgn.Online.StandAloneServer/Program.cs, octgnFX/Octgn.WindowsDesktopUtilities/Octgn.WindowsDesktopUtilities.csproj, octgnFX/Octgn.WindowsDesktopUtilities/OctgnProgram.cs
Don't built in key waiting into the OctgnProgram file, instead rely on a appconfig setting. Waiting for a key to exit is only useful for developers, so there's no need to have fancy switching logic for it, or even a command line switch.
Renamed the file Program to OctgnProgram
=> Fix for StandAloneServer not closing

octgnFX/Octgn.Core/DataManagers/GameManager.cs, octgnFX/Octgn/Play/Gui/Commands.cs, octgnFX/Octgn/Play/PlayWindow.xaml, octgnFX/Octgn/Play/PlayWindow.xaml.cs, recentchanges.txt
The play window now has a "Load Pre-Built Deck" menu item, which opens the file explorer directly inside the game installs Decks directory.
OCTGN will no longer dump the contents of this folder into the OCTGN's default decks folder whenever a game is installed/updated.
Once pushed live I recommend making a discord/twitter post that it's safe to delete all the game folders within OCTGN's default decks directory, as those are no longer used.
=> Changes how OCTGN handles game-bundled deck files

octgnFX/Octgn/CommandLineHandler.cs, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs, recentchanges.txt
- fixed decks being falsely flagged as unsaved when moving the cursor over the deck
- removed card counts from player/global editor tabs if they have no sections
- disabled editor deck tabs when no deck is loaded - #1895 
- Fixed crashes related to shared deck sections in the editor
=> various fixes for the deck editor

octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs, octgnFX/Octgn/Tabs/GameManagement/GameManagement.xaml, recentchanges.txt
turns out that card count was being set by a pre-update event, so now it updates after the change.
set high quality scaling for game images in the game manager tab.
=> fix editor card counts and improve scaling in game manager

LICENSE.md
There were a couple of Windows-1252 characters in the file, which I've fixed in this change.
=> Fixing Windows specific characters in the license

octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml, octgnFX/Octgn/DeckBuilder/DeckBuilderWindow.xaml.cs, recentchanges.txt
also cleaned up and generalized focusing things in the deck area.
=> resolve crash when activeSection was not on current tab

octgnFX/Octgn.Core/Prefs.cs, octgnFX/Octgn/Octgn.csproj, octgnFX/Octgn/Play/Dialogs/PreviewCardWindow.xaml, octgnFX/Octgn/Play/Dialogs/PreviewCardWindow.xaml.cs, octgnFX/Octgn/Play/PlayWindow.xaml, octgnFX/Octgn/Play/PlayWindow.xaml.cs
Adds a button in the play window to undock the card hover preview into its own resizeable window.  While active, the hover-over image overlay won't appear.
- additional controls within the window to scroll through the images of any alternates on the card (controls are hidden when there are no alternates)
- A checkbox to force proxy images to be shown
- The sizing and location of the window is saved into OCTGN's preferences
- respects the "hold CTRL to show proxy" mode from the hover preview options
Works with hovering card names in the chat, hovering over cards in piles, hovering cards in the Limited deck editor, and hovering cards within the "look at" group window.  Does not work with the Deck Stats sidebar (because that has its own image overlay (??)
=> Undockable card preview window

octgnFX/Octgn/Play/Gui/PlayerControl.xaml, octgnFX/Octgn/Play/PlayWindow.xaml.cs
the tabcontrol already has a selecteditem of the localplayer (and this is now the global player again anyway)
=> fixed global tab being selected

octgnFX/Octgn.Core/DataExtensionMethods/CardExtensionMethods.cs
Not really a big deal as this method is new and doesn't get used by OCTGN.  For people using our libraries (i.e. deck editor plugins), this should prevent some weird behavior
=> fixed an issue with the GetProperty card extension method

octgnFX/Octgn/Play/State/GameEngine.cs
With these changes, a deck which previously took ~10 seconds to load now loads in under 3 seconds.
Essentially, we have the Deck.Load() deck extension method that does the heavy lifting in translating a deck file into OCTGN.  It does all the DB querying to locate the matching cards, then stores them in the IDeck object.  This gets passed into the game engine.
So the game engine takes this IDeck file, iterates through the cards in each deck section, then ...queries the DB again to locate the card's image from its GUID?  Why are we querying for the card data when we already have it?
So I got rid of that section.
I've tested this with a bunch of different scenarios and it seems to work flawlessly.  Which makes me wonder... it can't be this simple, right?
=> better handling of deck loading

octgnFX/Octgn.Core/Prefs.cs, octgnFX/Octgn/Play/Dialogs/ChatWindow.xaml, octgnFX/Octgn/Play/Dialogs/ChatWindow.xaml.cs, octgnFX/Octgn/Play/Gui/ChatControl.xaml.cs, octgnFX/Octgn/Play/PlayWindow.xaml, octgnFX/Octgn/Play/PlayWindow.xaml.cs
This should  partially answer #1993 
Tested with Playing Cards and DigimonTCG, appears to have no side effects.
For people with large screens/dual screens, this gives plenty of space for the playerTabs.
Summary of changes
- Similar to PreviewCardWindow, the ChatWindow will save it's location in Prefs.
-  Added a new Menu in PlayWindow and moved existing "Undock Card Preview" under the new "Undock Options"
- Added "Undock Chat" in "Undock Options" menu
- Added Get method in chat control because it was causing VS xaml preview to crash
- Modified chat window keyboard focus code to include the new window
=> Undock options (Undock Chat)

octgnFX/Octgn/Play/PlayWindow.xaml.cs
This fixes the issue reported by Mitch below.
I added the event handler to the ChatWindow and tested that it works when docker or undocked. I'm not sure if there are anymore event handlers for the ChatControl. But think that is the only one it raises that I saw.
MitchYesterday at 4:02 PM
Found an issue with the "undock chat" it works fine except the preview when you hover in the chat box doesn't work
=> Undockchatpreviewfix

octgnFX/Octgn/Scripting/Versions/3.1.0.2.py, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs
I plan to use this for the save/load table state functionality in the Lord of the Rings plugin. I wanted to make it possible to use the system dialogs to choose the location to save the table state and the file to load it from.
I went for the simplest solution of exposing the system SaveFileDialog and OpenFileDialog via the script without adding another Control to Octgn/Scripting/Controls, which I tried initially, but ultimately wasn't necessary for my use case.
=> Added API calls for system save/load dialogs for use from scripts.

octgnFX/Octgn.Server/BinaryParser.cs, octgnFX/Octgn.Server/BinaryStubs.cs, octgnFX/Octgn.Server/Broadcaster.cs, octgnFX/Octgn.Server/Handler.cs, octgnFX/Octgn.Server/IClientCalls.cs, octgnFX/Octgn.Server/Protocol.xml, octgnFX/Octgn/Networking/BinaryParser.cs, octgnFX/Octgn/Networking/BinaryStubs.cs, octgnFX/Octgn/Networking/ClientHandler.cs, octgnFX/Octgn/Networking/IServerCalls.cs, octgnFX/Octgn/Play/Gui/TableControl.xaml.cs, octgnFX/Octgn/Play/State/GameEngine.cs, octgnFX/Octgn/Play/State/GameSaveState.cs, octgnFX/Octgn/Scripting/Versions/3.1.0.2.py, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_1.cs, octgnFX/Octgn/Scripting/Versions/Script_3_1_0_2.cs, octgnFX/o8build/GameValidator.cs, recentchanges.txt
change log has a summary of the updates.
Basically this cleans up some weird situations with game boards, allows python to remove the game board or set to the default board, and allows games to have no board set by default.
This doesn't fix the known issue with big game boards warping the play table's coordinate grids.
fixes #2013
=> Game board updates

octgnFX/Octgn.Core/GameFeedManager.cs, octgnFX/Octgn/AppConfig.cs, octgnFX/Octgn/GameUpdater.cs, octgnFX/Octgn/Program.cs, octgnFX/Octgn/Windows/UpdateChecker.xaml.cs
The ambition of this pull request is both to speed up the initial update check and to set a cap on how long the nuget feed scan is allowed to take.
It adds an AppSetting for "GameFeedTimeoutSeconds" which defaults to 60 seconds.
The nuget feed scanning is rewritten to be executed in parallel and has a maximum execution time set to "GameFeedTimeoutSeconds".
=> Feature: Timeout and parallel processing in GameFeedManager

octgnFX/Octgn.DataNew/Entities/Group.cs, octgnFX/Octgn.DataNew/GameSerializer.cs, octgnFX/Octgn.JodsEngine/Play/Group.cs, octgnFX/Octgn.JodsEngine/Play/Gui/GroupControl.cs, octgnFX/Octgn.JodsEngine/Play/PlayWindow.xaml.cs, octgnFX/Octgn.Library/Schemas/Game.cs, octgnFX/Octgn.Library/Schemas/Game.xsd, recentchanges.txt
optional 'shuffle' attribute for the group element, value is a hotkey string
hotkey follows the same hierarchy patterns as group and card actions
defaults to null, so it won't break existing shuffle python actions in games
=> closes #2050 - a default shuffle command for piles

octgnFX/Octgn.Core/DataManagers/GameManager.cs, octgnFX/Octgn.Library/ExtensionMethods/FileInfoExtensionMethods.cs
If the volumes are different, then Directory.MoveTo doesn't work.  This adds an extension method which handles this case by performing a traditional copy+delete alternative
=> fixed uninstalling games bug when graveyard path is in a different volume from the game database

octgnFX/Octgn/CommandLineHandler.cs, octgnFX/Octgn/Launchers/DeckEditorLauncher.cs, recentchanges.txt
Added a parameter to the launcher constructor so that the Shutdown property can be set by the caller.
Would be more self-documenting if this property could be set directly though, e.g.:
```
launcher = new DeckEditorLauncher(deckPath) { Shutdown = true };
```
=> End the launching process when using the -e parameter

octgnFX/Octgn.JodsEngine/Play/State/GameEngine.cs, recentchanges.txt
Possibly the existing logic is a bit unsound re: when to prompt for a new nickname, but this prevents the crash at least.
=> Avoid a null reference with Program.Dispatcher

octgnFX/Octgn.JodsEngine/DeckBuilder/DeckBuilderWindow.xaml.cs, octgnFX/Octgn.JodsEngine/DeckBuilder/SearchControl.xaml.cs, recentchanges.txt
After loading a search, the newly constructed object has a null _deckWindow, so just pass it in like with the other constructor.
=> Fix deckbuilder crash after loading a saved search

octgnFX/Octgn/JodsEngineIntegration.cs, recentchanges.txt
=> temp fix for hosting passworded online games

octgnFX/Octgn.JodsEngine/Play/Group.cs, octgnFX/Octgn.JodsEngine/Play/Gui/FanPanel.cs, octgnFX/Octgn.JodsEngine/Play/Gui/PileControl.xaml, octgnFX/Octgn.JodsEngine/Play/Gui/PileControl.xaml.cs
Closes #1875.
This change makes it so the expanded view animation when a card is moved to/from a pile is only shown to players which can see the pile.
It makes it impossible to, for example, notice which exactly card from an opponent's hand was played.
=> Removes movement animation when pile is hidden

octgnFX/Octgn.Core/DataExtensionMethods/CardExtensionMethods.cs, octgnFX/Octgn.JodsEngine/Scripting/Controls/CardDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_2.cs, recentchanges.txt
This improves the performance of these search filters, allowing them to properly match to null property values.
=> AskCard and QueryCard uses the same filter logic as the limited pack generator

octgnFX/Octgn.Core/Prefs.cs, octgnFX/Octgn.JodsEngine/DeckBuilder/SearchControl.xaml, octgnFX/Octgn.JodsEngine/DeckBuilder/SearchControl.xaml.cs, octgnFX/Octgn.JodsEngine/Play/Gui/CardControl.xaml.cs, octgnFX/Octgn.JodsEngine/Utils/Converters/RichTextConverter.cs, octgnFX/o8build/GameValidator.cs, recentchanges.txt
o8build will give a more useful error if you use richtext symbols in a set but don't have a symbols element in the game XML.
richtext symbol sizes will properly scale with the font size they are placed in
changed 'hide alternates' to 'show alternates' in deck editor for clarity
the 'show alternates' deck editor toggle state is now saved in config
=> Assorted fixes

octgnFX/Octgn.JodsEngine/Play/Card.cs, octgnFX/Octgn.JodsEngine/Play/Gui/CardControl.xaml, octgnFX/Octgn.JodsEngine/Play/State/GameEngine.cs, octgnFX/Octgn.JodsEngine/Scripting/Controls/ChoiceDlg.xaml, octgnFX/Octgn.JodsEngine/Scripting/Controls/ChoiceDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Controls/InputDlg.xaml, octgnFX/Octgn.JodsEngine/Scripting/Controls/InputDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Controls/SelectCardsDlg.xaml, octgnFX/Octgn.JodsEngine/Scripting/Controls/SelectCardsDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Controls/SelectMultiCardsDlg.xaml, octgnFX/Octgn.JodsEngine/Scripting/Controls/SelectMultiCardsDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Versions/3.1.0.2.py, octgnFX/Octgn.JodsEngine/Scripting/Versions/Script_3_1_0_2.cs, recentchanges.txt
Adds a card focus feature which darkens all cards in play (table, hand or piles) which aren't in the focus list.  NOTE that this does NOT network  to other players -- it stays local.
Added python controls to focus cards.
Hovering over cards in the SelectCards or SelectMultiCards python API dialogs will focus that card in play.
Also updates the inputDlg and choiceDlg API dialog boxes to pop open underneath the mouse cursor position, instead of in the middle of the play window.
=> Card focus feature and updates to in-game dialog windows

octgnFX/Octgn.DataNew/CardPropertyComparer.cs, octgnFX/Octgn.JodsEngine/Play/Dialogs/LimitedDialog.xaml, octgnFX/Octgn.JodsEngine/Play/Dialogs/LimitedDialog.xaml.cs, octgnFX/Octgn.JodsEngine/Play/Dialogs/PickCardsDialog.xaml, octgnFX/Octgn.JodsEngine/Play/Dialogs/PickCardsDialog.xaml.cs, octgnFX/Octgn.JodsEngine/Play/Gui/CardControl.xaml, octgnFX/Octgn.JodsEngine/Play/Gui/TableCanvas.cs, octgnFX/Octgn.JodsEngine/Resources/PlayResources.xaml, octgnFX/Octgn.JodsEngine/Scripting/Controls/ChoiceDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Controls/InputDlg.xaml.cs, octgnFX/Octgn.JodsEngine/Scripting/Engine.cs, octgnFX/Octgn.JodsEngine/Utils/Converters/BooleanToVisibleHiddenConverter.cs, octgnFX/Octgn/Resources/PlayResources.xaml, octgnFX/Octgn/Utils/Converters/BooleanToVisibleHiddenConverter.cs
Fixes/Changes included:
- Add a Fade-In/Fade-Out for Focused cards.
- Fix issue caused by null reference exception when trying to join password protected rooms, and center every input and choice dialog window
- Fix issue caused by skipping `targetAction.FromCard.TargetsOtherCards = false;`.
- Add a more accurate sorting to Limited Game Window (sorting by two last choices).
- Add a Return button to quickly return all cards in Deck to Limited Card Pool.
- Attempt to sort the filters in Limited Game more naturally (instead of sorting 1->10->2, we try to sort 1->2->10 if possible):
- Allow adding more than one Pack at a time in the Start Limited Game window:
=> Szefo patches

deploy/Heat-FileList-README.md, deploy/Update-HeatFileList.ps1, deploy/update-heat-filelist.bat, octgnFX/Octgn.InstallerLib/HeatGeneratedFileList.wxs, octgnFX/Octgn.InstallerLib/Octgn.InstallerLib.wixproj
- Add PowerShell script to generate WiX Heat file list while preserving existing component GUIDs
- Remove automatic Heat generation from MSBuild process
- Script intelligently detects when regeneration is needed based on actual file changes
- Filters out .pdb, .xml, data.path, and logs files (same as XSLT transform)
- Provides detailed reporting of new/removed/modified files
- Includes batch file wrapper for easy execution
- Maintains upgrade compatibility by preserving component identities
Usage: deploy\update-heat-filelist.bat [Debug|Release] [-Force]
=> Add Heat file list generator with GUID preservation
